import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_KR } from "next/font/google";
import "./globals.css";
import MainNav from "@/component/main-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifKR = Noto_Serif_KR({
  variable: "--font-noto-serif-kr",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerifKR.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col min-w-[1000px]">
          <header className="flex h-35 items-center border-b border-gray-200 px-6">
            <div className="mx-auto flex h-full items-center justify-cente">
              <div className="font-mantra text-[40px] font-bold">
                대불정수능엄신주
              </div>
            </div>
          </header>

          <MainNav />

          <main className="flex flex-1 flex-col min-w-[1000px]">
            {children}
          </main>

          <footer className="border-t border-gray-200 px-6 py-3 text-xs">
            <div className="mx-auto flex items-center justify-center gap-4 h-5">
              <span>© {new Date().getFullYear()} 능엄주 암기 노트</span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
