import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_KR } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifKR = Noto_Serif_KR({
  variable: "--font-noto-serif-kr",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LAYOUT_TOP_BOTTOM_PX = 140 + 64 + 48;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerifKR.variable} antialiased`}
      >
        <div className="flex min-h-screen flex-col min-w-[1000px]">
          <header className="flex h-35 items-center border-b border-gray-200 px-6">
            <div className="mx-auto flex h-full items-center justify-center">
              <div className="font-mantra text-[40px] font-semibold">
                대불정수능엄신주
              </div>
            </div>
          </header>

          <nav className="flex h-16 w-full items-center border-b border-gray-200">
            <div className="mx-auto flex h-full w-[800px] items-center justify-between gap-12 text-2xl">
              <div className="flex h-full cursor-pointer items-center border-b-3 border-transparent text-gray-500 hover:text-gray-900">
                홈
              </div>
              <div className="flex h-full cursor-pointer items-center border-b-3 border-gray-900 font-medium text-gray-900 hover:text-gray-900">
                연습하기
              </div>
              <div className="flex h-full cursor-pointer items-center border-b-3 border-transparent text-gray-500 hover:text-gray-900">
                암기하기
              </div>
              <div className="flex h-full cursor-pointer items-center border-b-3 border-transparent text-gray-500 hover:text-gray-900">
                설정
              </div>
            </div>
          </nav>

          <main
            className="flex-1"
            style={{ minHeight: `calc(100vh - ${LAYOUT_TOP_BOTTOM_PX}px)` }}
          >
            {children}
          </main>

          <footer className="border-t border-gray-200 px-6 py-3 text-xs">
            <div className="mx-auto flex items-center justify-center gap-4">
              <span>© {new Date().getFullYear()} 능엄주 암기 노트</span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
