"use client";

import YoutubeVideoCard from "@/component/more/youtube-video-card";

export default function MoreVideoPage() {
  return (
    <div className="mx-auto h-full w-[1000px]">
      <section className="grid grid-cols-2 overflow-hidden divide-x divide-gray-200">
        <YoutubeVideoCard
          title="능엄주 (대불정능엄신주)"
          videoId="_Y8S2dBOM04"
          href="https://www.youtube.com/watch?v=_Y8S2dBOM04"
          sourceLabel="출처: YouTube (Auto-generated by YouTube)"
        />
        <YoutubeVideoCard
          title="능엄주 7독, 정원스님 독송 / 대불정다라니(大佛頂陁羅尼)"
          videoId="i3jh-ZHzQTk"
          href="https://www.youtube.com/watch?v=i3jh-ZHzQTk&t=1361s"
          sourceLabel="출처: YouTube SereneSky[적천]"
        />
        <YoutubeVideoCard
          title="원행스님, 대불정 능엄신주 독경"
          videoId="idpmk6-gQv4"
          href="https://www.youtube.com/watch?v=idpmk6-gQv4"
          sourceLabel="출처: YouTube 백련불교문화재단_성철사상연구원"
          isLast={true}
          /> 
      </section>
      {/* <section className="flex h-full w-full min-w-0 flex-col overflow-hidden">
        <YoutubeVideoCard
          title="능엄주 (대불정능엄신주)"
          videoId="_Y8S2dBOM04"
          href="https://www.youtube.com/watch?v=_Y8S2dBOM04"
          sourceLabel="출처: YouTube (Auto-generated by YouTube)"
        />
        <YoutubeVideoCard
          title="능엄주 7독, 정원스님 독송 / 대불정다라니(大佛頂陁羅尼)"
          videoId="i3jh-ZHzQTk"
          href="https://www.youtube.com/watch?v=i3jh-ZHzQTk&t=1361s"
          sourceLabel="출처: YouTube SereneSky[적천]"
        />
        <YoutubeVideoCard
          title="원행스님, 대불정 능엄신주 독경"
          videoId="idpmk6-gQv4"
          href="https://www.youtube.com/watch?v=idpmk6-gQv4"
          sourceLabel="출처: YouTube 백련불교문화재단_성철사상연구원"
          isLast={true}
        />
      </section> */}
    </div>
  );
}
